openapi: 3.0.0
info:
  title: API - Sistema de Ordens de Serviço
  version: 1.0.0
  description: API RESTful em PHP para gerenciar clientes, produtos e ordens de serviço, com autenticação JWT.

servers:
  - url: http://ordemservico/public/api.php

paths:
  /api.php?resource=login:
    post:
      tags:
        - Auth
      summary: Autentica um usuário
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                senha:
                  type: string
      responses:
        '200':
          description: Token JWT retornado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  token:
                    type: string
                  expires_in:
                    type: integer
                  token_type:
                    type: string
        '401':
          description: Credenciais inválidas

  /clientes:
    get:
      summary: Listar todos os clientes
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Lista de clientes
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    nome:
                      type: string
                      example: "João Silva"
                    email:
                      type: string
                      format: email
                      example: "joao@example.com"
                    documento:
                      type: string
                      example: "123.456.789-09"
                    logradouro:
                      type: string
                      example: "Rua das Flores"
                    numero:
                      type: string
                      example: "123"
                    complemento:
                      type: string
                      nullable: true
                      example: "Apto 101"
                    bairro:
                      type: string
                      example: "Centro"
                    cidade:
                      type: string
                      example: "São Paulo"
                    uf:
                      type: string
                      example: "SP"
                    cep:
                      type: string
                      example: "01001-000"
        '401':
          description: Credenciais inválidas          
    post:
      summary: Criar um novo cliente
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                email:
                  type: string
      responses:
        '201':
          description: Cliente criado
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    nome:
                      type: string
                      example: "João Silva"
                    email:
                      type: string
                      format: email
                      example: "joao@example.com"
                    documento:
                      type: string
                      example: "123.456.789-09"
                    logradouro:
                      type: string
                      example: "Rua das Flores"
                    numero:
                      type: string
                      example: "123"
                    complemento:
                      type: string
                      nullable: true
                      example: "Apto 101"
                    bairro:
                      type: string
                      example: "Centro"
                    cidade:
                      type: string
                      example: "São Paulo"
                    uf:
                      type: string
                      example: "SP"
                    cep:
                      type: string
                      example: "01001-000"
          

  /clientes/{id}:
    get:
      summary: Obter cliente por ID
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Cliente retornado
    put:
      summary: Atualizar cliente
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                email:
                  type: string
      responses:
        '200':
          description: Cliente atualizado
    delete:
      summary: Remover cliente
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Cliente removido

  /produtos:
    get:
      summary: Listar todos os produtos
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Lista de produtos
    post:
      summary: Criar um novo produto
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                preco:
                  type: number
      responses:
        '201':
          description: Produto criado

  /produtos/{id}:
    get:
      summary: Obter produto por ID
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Produto retornado
    put:
      summary: Atualizar produto
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                preco:
                  type: number
      responses:
        '200':
          description: Produto atualizado
    delete:
      summary: Remover produto
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Produto removido

  /ordens:
    get:
      summary: Listar ordens de serviço
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Lista de ordens
    post:
      summary: Criar nova ordem de serviço
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                cliente_id:
                  type: integer
                produto_id:
                  type: integer
                descricao:
                  type: string
      responses:
        '201':
          description: Ordem criada

  /ordens/{id}:
    get:
      summary: Obter ordem por ID
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Ordem retornada
    put:
      summary: Atualizar ordem de serviço
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                cliente_id:
                  type: integer
                produto_id:
                  type: integer
                descricao:
                  type: string
      responses:
        '200':
          description: Ordem atualizada
    delete:
      summary: Remover ordem de serviço
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Ordem removida

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
